#!/usr/local/bin/python

import sys

from src.ingestions import update_games
from src.utils import get_available_seasons

if __name__ == "__main__":
    if '-a' in sys.argv[1:]:
        all_flag = True
    else:
        all_flag = False

    if all_flag:
        seasons = None
    else:
        seasons = get_available_seasons()[-1:]

    update_games(seasons)
