#!/usr/local/bin/python

import sys

from src.ingestions import update_games
from src.utils import get_available_seasons

if __name__ == "__main__":
    all_flag = '-a' in sys.argv[1:]

    if all_flag:
        seasons = None
    else:
        seasons = get_available_seasons()[-1:]

    update_games(seasons)
